<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cql</string>
		<string>cyp</string>
	</array>
	<key>name</key>
	<string>Cypher</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constants</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#functions</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#path-patterns</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#identifiers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#properties_literal</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numbers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>//.*$\n?</string>
					<key>name</key>
					<string>comment.line.double-slash.cypher</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\bTRUE|true|FALSE|false\b</string>
					<key>name</key>
					<string>constant.language.bool.cypher</string>
				</dict>
			</array>
		</dict>
		<key>functions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>List of Cypher built-in functions from https://neo4j.com/docs/cypher-manual/current/keyword-glossary/</string>
					<key>match</key>
					<string>(?i)\b(ACOS|ASIN|ATAN|ATAN2|COS|COT|DEGREES|HAVERSIN|PI|RADIANS|SIN|TAN)(?=\s*\()</string>
					<key>name</key>
					<string>support.function.trigonometric.cypher</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>List of Cypher built-in functions from https://neo4j.com/docs/cypher-manual/current/keyword-glossary/</string>
					<key>match</key>
					<string>(?i)\b(NOT)(?=\s*\()</string>
					<key>name</key>
					<string>keyword.control.function.boolean.cypher</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>List of Cypher built-in functions from https://neo4j.com/docs/cypher-manual/current/keyword-glossary/</string>
					<key>match</key>
					<string>(?i)\b(DISTANCE|POINT)(?=\s*\()</string>
					<key>name</key>
					<string>support.function.spatial.cypher</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>List of Cypher built-in functions from https://neo4j.com/docs/cypher-manual/current/keyword-glossary/</string>
					<key>match</key>
					<string>(?i)\b(DATE|DATE\.REALTIME|DATE\.STATEMENT|DATE\.TRANSACTION|DATE\.TRUNCATE|DATETIME|DATETIME\.REALTIME|DATETIME\.STATEMENT|DATETIME\.TRANSACTION|DATETIME\.TRUNCATE|DURATION|DURATION\.BETWEEN|DURATION\.INDAYS|DURATION\.INMONTHS|DURATION\.INSECONDS|LOCALDATETIME|LOCALDATETIME\.REALTIME|LOCALDATETIME\.STATEMENT|LOCALDATETIME\.TRANSACTION|LOCALDATETIME\.TRUNCATE|LOCALTIME|LOCALTIME\.REALTIME|LOCALTIME\.STATEMENT|LOCALTIME\.TRANSACTION|LOCALTIME\.TRUNCATE|TIME|TIME\.REALTIME|TIME\.STATEMENT|TIME\.TRANSACTION|TIME\.TRUNCATE)(?=\s*\()</string>
					<key>name</key>
					<string>support.function.temporal.cypher</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>List of Cypher built-in functions from https://neo4j.com/docs/cypher-manual/current/keyword-glossary/</string>
					<key>match</key>
					<string>(?i)\b(KEYS|LABELS|NODES|RANGE|REDUCE|RELATIONSHIPS|REVERSE|TAIL)(?=\s*\()</string>
					<key>name</key>
					<string>support.function.list.cypher</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>List of Cypher built-in functions from https://neo4j.com/docs/cypher-manual/current/keyword-glossary/</string>
					<key>match</key>
					<string>(?i)\b(E|EXP|LOG|LOG10|SQRT)(?=\s*\()</string>
					<key>name</key>
					<string>support.function.logarithmic.cypher</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>List of Cypher built-in functions from https://neo4j.com/docs/cypher-manual/current/keyword-glossary/</string>
					<key>match</key>
					<string>(?i)\b(ALL|ANY|EXISTS|NONE|SINGLE)(?=\s*\()</string>
					<key>name</key>
					<string>support.function.predicate.cypher</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>List of Cypher built-in functions from https://neo4j.com/docs/cypher-manual/current/keyword-glossary/</string>
					<key>match</key>
					<string>(?i)\b(NODES|RELATIONSHIPS|EXTRACT|FILTER|TAIL|RANGE|REDUCE)(?=\s*\()</string>
					<key>name</key>
					<string>support.function.collection.cypher</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>List of Cypher built-in functions from https://neo4j.com/docs/cypher-manual/current/keyword-glossary/</string>
					<key>match</key>
					<string>(?i)\b(ABS|CEIL|FLOOR|RAND|ROUND|SIGN)(?=\s*\()</string>
					<key>name</key>
					<string>support.function.numeric.cypher</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>List of Cypher built-in functions from https://neo4j.com/docs/cypher-manual/current/keyword-glossary/</string>
					<key>match</key>
					<string>(?i)\b(AVG|COLLECT|COUNT|MAX|MIN|PERCENTILECONT|PERCENTILEDISC|STDEV|STDEVP|SUM)(?=\s*\()</string>
					<key>name</key>
					<string>support.function.aggregation.cypher</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>List of Cypher built-in functions from https://neo4j.com/docs/cypher-manual/current/keyword-glossary/</string>
					<key>match</key>
					<string>(?i)\b(LEFT|LTRIM|REPLACE|RIGHT|RTRIM|SPLIT|SUBSTRING|TOLOWER|TOSTRING|TOUPPER|TRIM)(?=\s*\()</string>
					<key>name</key>
					<string>support.function.string.cypher</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>List of Cypher built-in functions from https://neo4j.com/docs/cypher-manual/current/keyword-glossary/</string>
					<key>match</key>
					<string>(?i)\b(COALESCE|ENDNODE|HEAD|ID|LAST|LENGTH|PROPERTIES|RANDOMUUID|SIZE|STARTNODE|TIMESTAMP|TOBOOLEAN|TOFLOAT|TOINTEGER|TYPE)(?=\s*\()</string>
					<key>name</key>
					<string>support.function.scalar.cypher</string>
				</dict>
			</array>
		</dict>
		<key>identifiers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>`.+?`</string>
					<key>name</key>
					<string>variable.other.quoted-identifier.cypher</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[a-zA-Z_][a-zA-Z0-9_]*</string>
					<key>name</key>
					<string>variable.other.identifier.cypher</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b(ALTER|ALTER\s+CURRENT\s+USER|AS|ASSERT|CALL|CHANGE\s+NOT\s+REQUIRED|CHANGE\s+REQUIRED|COPY\s+OF|CREATE|CREATE\s+CONSTRAINT|CREATE\s+INDEX|CYPHER|DELETE|DENY|DETACH\s+DELETE|DISTINCT|DROP|EXISTS|FOR|FOREACH|FROM|GRANT|LIMIT|LOAD\s+CSV|MATCH|MERGE|ON|ON\s+CREATE|ON\s+MATCH|OPTIONAL|ORDER\s+BY|POPULATED|REMOVE|RETURN|REVOKE|ROLE|ROLES|SET|SET\s+PASSWORD|SET\s+STATUS\s+ACTIVE|SET\s+STATUS\s+SUSPENDED|SKIP|START|TO|UNION|UNION\s+ALL|UNIQUE|UNWIND|USE|USERS|USING\s+INDEX|USING\s+INDEX\s+SEEK|USING\s+JOIN\s+ON|USING\s+PERIODIC\s+COMMIT|USING\s+SCAN|WHERE|WITH|YIELD)\b</string>
					<key>name</key>
					<string>keyword.control.clause.cypher</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(DESC|DESCENDING|ASC|ASCENDING)\b</string>
					<key>name</key>
					<string>keyword.other.order.cypher</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)\b(node|relationship|rel)((:)([a-zA-Z_-][a-zA-Z0-9_]*))?(?=\s*\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.starting-functions-point.cypher</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.index-seperator.cypher</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.control.index-seperator.cypher</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>support.class.index.cypher</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>name</key>
					<string>source.starting-functions.cypher</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>((?:`.+?`)|(?:[a-zA-Z_][a-zA-Z0-9_]*))</string>
							<key>name</key>
							<string>variable.parameter.relationship-name.cypher</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(\*)</string>
							<key>name</key>
							<string>keyword.control.starting-function-params,cypher</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#numbers</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#strings</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>numbers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b\d+(\.\d+)?\b</string>
					<key>name</key>
					<string>constant.numeric.cypher</string>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\+|\-|\/|\*|\%|\?|!)</string>
					<key>name</key>
					<string>keyword.operator.math.cypher</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(&lt;=|=&gt;|&lt;&gt;|&lt;|&gt;|=~|=)</string>
					<key>name</key>
					<string>keyword.operator.compare.cypher</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(OR|AND)\b</string>
					<key>name</key>
					<string>keyword.operator.logical.cypher</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(IN)\b</string>
					<key>name</key>
					<string>keyword.operator.in.cypher</string>
				</dict>
			</array>
		</dict>
		<key>path-patterns</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(&lt;--|--&gt;|--)</string>
					<key>name</key>
					<string>support.function.relationship-pattern.cypher</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(&lt;-|-)(\[)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.relationship-pattern-start.cypher</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.relationship-pattern-start.cypher</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(])(-&gt;|-)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.relationship-patern-end.cypher</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.function.relationship-pattern-start.cypher</string>
						</dict>
					</dict>
					<key>name</key>
					<string>path-pattern.cypher</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#identifiers</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.relationship-type-start.cypher</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.class.relationship.type.cypher</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(:)((?:`.+?`)|(?:[a-zA-Z_][a-zA-Z0-9_]*))</string>
							<key>name</key>
							<string>entity.name.class.relationship-type.cypher</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>support.type.operator.relationship-type-or.cypher</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.class.relationship.type-or.cypher</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(\|)(\s*)((?:`.+?`)|(?:[a-zA-Z_][a-zA-Z0-9_]*))</string>
							<key>name</key>
							<string>entity.name.class.relationship-type-ored.cypher</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:\?\*|\?|\*)\s*(?:\d+\s*(?:\.\.\s*\d+)?)?</string>
							<key>name</key>
							<string>support.function.relationship-pattern.quant.cypher</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#properties_literal</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>properties_literal</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>{</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.properties_literal.cypher</string>
						</dict>
					</dict>
					<key>end</key>
					<string>}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.properties_literal.cypher</string>
						</dict>
					</dict>
					<key>name</key>
					<string>source.cypher</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>:|,</string>
							<key>name</key>
							<string>keyword.control.properties_literal.seperator.cypher</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#constants</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#functions</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#operators</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#identifiers</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#numbers</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#strings</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>string_escape</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.cypher</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\\\\|\\[tbnrf])|(\\'|\\")</string>
			<key>name</key>
			<string>constant.character.escape.cypher</string>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>string.quoted.single.cypher</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_escape</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double.cypher</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_escape</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.cypher</string>
	<key>uuid</key>
	<string>698F4D06-BAE8-40A8-8AA4-3307ABC03B31</string>
</dict>
</plist>